# version: "3.9"
x-app-common: &app-common
  build: .
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/enterprise_db
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: 1234567
    SPRING_JPA_HIBERNATE_DDL_AUTO: update

    APP_STORAGE_PROVIDER: s3
    APP_STORAGE_BUCKET: alberto-enterprise-avatars-2026
    APP_AWS_REGION: us-west-2

    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    APP_CACHE_PROVIDER: redis
    SPRING_DATA_REDIS_HOST: redis
    SPRING_DATA_REDIS_PORT: 6379
  expose:
    - "8080"
  volumes:
    - uploads:/app/uploads
  healthcheck:
    test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep -q UP"]
    interval: 10s
    timeout: 3s
    retries: 10

services:
  db:
    image: postgres:17
    container_name: enterprise-db
    environment:
      POSTGRES_DB: enterprise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d enterprise_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - enterprise-net
  # Replica 1
  app1:
     <<: *app-common
     container_name: enterprise-api-1
     networks:
       - enterprise-net

  # Replica 2
  app2:
     <<: *app-common
     container_name: enterprise-api-2
     networks:
       - enterprise-net

  # Load Balancer (tu API ahora se consume por aquí)
  nginx:
    image: nginx:1.27-alpine
    container_name: enterprise-nginx
    depends_on:
     app1:
       condition: service_healthy
     app2:
       condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - enterprise-net

  prometheus:
    image: prom/prometheus:latest
    container_name: enterprise-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app1
      - app2
    networks:
      - enterprise-net
  grafana:
    image: grafana/grafana:latest
    container_name: enterprise-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
     - enterprise-net
  redis:
    image: redis:7-alpine
    container_name: enterprise-redis
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
     - enterprise-net
volumes:
  pgdata:
  uploads:
  grafana-data:
  redis-data:
networks:
  enterprise-net:
    driver: bridge