spring:
  application:
    name: enterprise-clean-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/enterprise_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234567}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
   storage:
     provider: ${APP_STORAGE_PROVIDER:local}
     bucket: ${APP_STORAGE_BUCKET:}
   aws:
     region: ${APP_AWS_REGION:us-west-2}
management:
   endpoints:
     web:
       exposure:
         include: health,info,prometheus
   endpoint:
     health:
       show-details: always
       probes:
         enable: true